import {
  SeasonalEventTemplate,
  CandidateAction,
  CustomerSeasonalEvaluation,
  SeasonalCampaignCalendarCard,
  CampaignLearningReport,
  BudgetAllocation
} from "./types";

// ─── CANDIDATE ACTIONS LIBRARY ───────────────────────────────────────────────

export const CANDIDATE_ACTIONS: Record<string, CandidateAction> = {
  // Promotional Actions
  cashback_admission: {
    id: "act-promo-adm-10",
    name: "10% Admission Fee Cashback",
    category: "Promotional",
    type: "cashback_admission",
    description: "10% instant cashback (up to ৳300) on tuition or university admission fees.",
    unitCostBDT: 150,
    defaultDiscountValue: "10% (max ৳300)",
    channel: "Push Notification",
    optimalTime: "7:30 PM",
  },
  cashback_recharge: {
    id: "act-promo-rech-20",
    name: "20% Recharge Cashback",
    category: "Promotional",
    type: "cashback_recharge",
    description: "20% bonus recharge on ৳100+ mobile pack for active telecom operators.",
    unitCostBDT: 25,
    defaultDiscountValue: "20% (max ৳50)",
    channel: "SMS",
    optimalTime: "11:00 AM",
  },
  cashback_merchant: {
    id: "act-promo-merch-15",
    name: "15% Merchant QR Cashback",
    category: "Promotional",
    type: "cashback_merchant",
    description: "15% cashback on QR retail payments at 25,000+ verified Upay partner outlets.",
    unitCostBDT: 75,
    defaultDiscountValue: "15% (max ৳200)",
    channel: "Push Notification",
    optimalTime: "5:00 PM",
  },
  cashback_salami: {
    id: "act-promo-eid-salami",
    name: "10% Eid Salami Cashback",
    category: "Promotional",
    type: "cashback_send_money",
    description: "Free Send Money + ৳25 cashback bonus on sending Salami to family and friends.",
    unitCostBDT: 25,
    defaultDiscountValue: "৳25 Flat Cashback",
    channel: "Push Notification",
    optimalTime: "8:00 PM",
  },
  reward_gift_card: {
    id: "act-promo-giftcard",
    name: "৳50 Lifestyle Gift Voucher",
    category: "Promotional",
    type: "reward_gift_card",
    description: "Digital lifestyle voucher unlocked after completing 2 festive transactions.",
    unitCostBDT: 50,
    defaultDiscountValue: "৳50 Voucher",
    channel: "In-App Banner",
    optimalTime: "6:30 PM",
  },
  reward_referral: {
    id: "act-promo-student-ref",
    name: "Student Referral Bonus (৳50 each)",
    category: "Promotional",
    type: "reward_referral",
    description: "Earn ৳50 for both you and your classmate upon their first admission payment.",
    unitCostBDT: 50,
    defaultDiscountValue: "৳50 Dual Bonus",
    channel: "Push Notification",
    optimalTime: "4:00 PM",
  },

  // Non-Promotional Actions (Cost = ৳0)
  reminder_admission: {
    id: "act-nonpromo-adm-reminder",
    name: "Admission Deadline Reminder",
    category: "Non-Promotional",
    type: "reminder_payment",
    description: "Helpful informational alert: University admission portal closing in 48 hours.",
    unitCostBDT: 0,
    channel: "Push Notification",
    optimalTime: "10:30 AM",
  },
  reminder_utility: {
    id: "act-nonpromo-util-reminder",
    name: "Month-End Utility Bill Reminder",
    category: "Non-Promotional",
    type: "reminder_payment",
    description: "DESCO / DPDC electricity bill due in 3 days. Pay directly with zero surcharge.",
    unitCostBDT: 0,
    channel: "In-App Banner",
    optimalTime: "9:00 AM",
  },
  reminder_recharge: {
    id: "act-nonpromo-rech-nudge",
    name: "Low Balance Telecom Nudge",
    category: "Non-Promotional",
    type: "reminder_recharge",
    description: "Gentle nudge to maintain data balance during online lecture and exam week.",
    unitCostBDT: 0,
    channel: "SMS",
    optimalTime: "1:00 PM",
  },
  insight_money: {
    id: "act-nonpromo-insight",
    name: "Personalized Spending Insight",
    category: "Non-Promotional",
    type: "insight_money",
    description: "You saved ৳420 last month across bill payments and merchant shopping!",
    unitCostBDT: 0,
    channel: "In-App Banner",
    optimalTime: "8:30 PM",
  },
  message_eid_greeting: {
    id: "act-nonpromo-greeting",
    name: "Eid Mubarak Personalized Greeting",
    category: "Non-Promotional",
    type: "message_reengagement",
    description: "Warm festive greeting from Upay with no promotional push to respect user peace.",
    unitCostBDT: 0,
    channel: "In-App Banner",
    optimalTime: "9:00 AM",
  },

  // Mandatory "No Promotional Action" (Organic Protection / Churn Suppression)
  no_promotional_action: {
    id: "act-no-action",
    name: "No Promotional Action",
    category: "No Promotional Action",
    type: "no_action",
    description: "Zero intervention. Customer is organically transacting or exhibiting high fatigue.",
    unitCostBDT: 0,
    channel: "In-App Banner",
    optimalTime: "N/A",
  },
};

// ─── EVENT TEMPLATES (SECTION 1 & 2) ─────────────────────────────────────────

export const SEASONAL_TEMPLATES: SeasonalEventTemplate[] = [
  {
    id: "university_admission",
    name: "University Admission Season",
    icon: "🎓",
    badgeColor: "bg-blue-100 text-blue-800 border-blue-200",
    description: "Target incoming undergraduates and parents during major public/private university intake windows.",
    startDate: "2026-10-01",
    endDate: "2026-10-31",
    businessObjective: "Increase education-related payment transactions and acquire/activate student customers.",
    targetProduct: "Education & Tuition Payments",
    availableBudgetBDT: 280000,
    maxCampaignCapacity: 12000,
    eligibleCustomerSegments: ["New Users", "Activation Stage", "Young Adults (18-24)", "Campus Ambassadors"],
    preferredChannels: ["Push Notification", "In-App Banner", "SMS"],
    candidateOffers: [
      CANDIDATE_ACTIONS.cashback_admission,
      CANDIDATE_ACTIONS.reward_referral,
      CANDIDATE_ACTIONS.reminder_admission,
      CANDIDATE_ACTIONS.cashback_recharge,
      CANDIDATE_ACTIONS.no_promotional_action,
    ],
    possibleBehaviors: [
      { name: "Admission Fee Payment", relevanceRate: 0.82 },
      { name: "New User Registration & KYC", relevanceRate: 0.74 },
      { name: "Student Peer Referral", relevanceRate: 0.65 },
      { name: "First Mobile Recharge", relevanceRate: 0.58 },
      { name: "Campus Canteen QR Payment", relevanceRate: 0.42 },
    ],
  },
  {
    id: "eid_ul_fitr",
    name: "Eid-ul-Fitr (Salami & Gifting)",
    icon: "🌙",
    badgeColor: "bg-emerald-100 text-emerald-800 border-emerald-200",
    description: "Capitalize on Bangladesh's peak peer-to-peer festive remittance and retail shopping season.",
    startDate: "2026-03-15",
    endDate: "2026-04-05",
    businessObjective: "Maximize incremental Send Money (Salami) GMV and merchant retail POS adoption.",
    targetProduct: "Send Money & Merchant QR",
    availableBudgetBDT: 550000,
    maxCampaignCapacity: 25000,
    eligibleCustomerSegments: ["P2P High Frequency", "Salaried Remitters", "Family Heads", "Youth"],
    preferredChannels: ["Push Notification", "In-App Banner"],
    candidateOffers: [
      CANDIDATE_ACTIONS.cashback_salami,
      CANDIDATE_ACTIONS.reward_gift_card,
      CANDIDATE_ACTIONS.cashback_merchant,
      CANDIDATE_ACTIONS.message_eid_greeting,
      CANDIDATE_ACTIONS.no_promotional_action,
    ],
    possibleBehaviors: [
      { name: "Send Money (Salami)", relevanceRate: 0.88 },
      { name: "Eid Fashion Shopping", relevanceRate: 0.76 },
      { name: "Family Inter-City Remittance", relevanceRate: 0.71 },
      { name: "Festive Mobile Recharge", relevanceRate: 0.62 },
      { name: "Zakat & Charitable Donation", relevanceRate: 0.49 },
    ],
  },
  {
    id: "salary_month_end",
    name: "Salary / Month-End Cycle",
    icon: "💼",
    badgeColor: "bg-indigo-100 text-indigo-800 border-indigo-200",
    description: "Align with the 25th-5th payday window when households execute bill settlements and savings deposits.",
    startDate: "2026-10-25",
    endDate: "2026-11-05",
    businessObjective: "Drive utility bill settlements and recurring DPS / wallet cash-in habituation.",
    targetProduct: "Bill Payment & DPS Savings",
    availableBudgetBDT: 200000,
    maxCampaignCapacity: 15000,
    eligibleCustomerSegments: ["Salaried Tier", "Home Managers", "Active Bill Payers"],
    preferredChannels: ["Push Notification", "In-App Banner", "SMS"],
    candidateOffers: [
      CANDIDATE_ACTIONS.reminder_utility,
      CANDIDATE_ACTIONS.insight_money,
      CANDIDATE_ACTIONS.cashback_recharge,
      CANDIDATE_ACTIONS.no_promotional_action,
    ],
    possibleBehaviors: [
      { name: "Electricity / Water / Gas Bill Pay", relevanceRate: 0.89 },
      { name: "Salary Cash-In from Bank", relevanceRate: 0.81 },
      { name: "Monthly Grocery QR Payment", relevanceRate: 0.67 },
      { name: "Recurring Savings (DPS)", relevanceRate: 0.54 },
    ],
  },
  {
    id: "shopping_season",
    name: "Shopping Season & Flash Deals",
    icon: "🛒",
    badgeColor: "bg-amber-100 text-amber-800 border-amber-200",
    description: "Seasonal e-commerce and retail sale surges including Pohela Boishakh and 11.11 shopping waves.",
    startDate: "2026-10-15",
    endDate: "2026-10-30",
    businessObjective: "Boost merchant payment volume and grow retail partner merchant margins.",
    targetProduct: "Merchant POS & Online Gateway",
    availableBudgetBDT: 170000,
    maxCampaignCapacity: 9000,
    eligibleCustomerSegments: ["Urban Shoppers", "Credit Card / MFS Power Users", "Retention Cohort"],
    preferredChannels: ["Push Notification", "In-App Banner"],
    candidateOffers: [
      CANDIDATE_ACTIONS.cashback_merchant,
      CANDIDATE_ACTIONS.reward_gift_card,
      CANDIDATE_ACTIONS.insight_money,
      CANDIDATE_ACTIONS.no_promotional_action,
    ],
    possibleBehaviors: [
      { name: "E-Commerce Checkout", relevanceRate: 0.84 },
      { name: "Restaurant & Cafe QR Pay", relevanceRate: 0.73 },
      { name: "Electronics & Gadget Purchase", relevanceRate: 0.59 },
    ],
  },
  {
    id: "ramadan",
    name: "Ramadan Mubarak",
    icon: "🕌",
    badgeColor: "bg-purple-100 text-purple-800 border-purple-200",
    description: "Evening Iftar dining, charitable giving, and nighttime bill settlements during the holy month.",
    startDate: "2026-02-15",
    endDate: "2026-03-15",
    businessObjective: "Promote donation collections, grocery payments, and night-owl mobile recharge bundles.",
    targetProduct: "Donations & Food QR",
    availableBudgetBDT: 180000,
    maxCampaignCapacity: 10000,
    eligibleCustomerSegments: ["Donors", "Grocery Shoppers", "Active Base"],
    preferredChannels: ["In-App Banner", "Push Notification"],
    candidateOffers: [
      CANDIDATE_ACTIONS.cashback_merchant,
      CANDIDATE_ACTIONS.reminder_utility,
      CANDIDATE_ACTIONS.no_promotional_action,
    ],
    possibleBehaviors: [
      { name: "Zakat & Charity Transfer", relevanceRate: 0.86 },
      { name: "Iftar / Sehri Dining QR", relevanceRate: 0.77 },
      { name: "Night-time Recharge", relevanceRate: 0.68 },
    ],
  },
  {
    id: "pohela_boishakh",
    name: "Pohela Boishakh (Bangla New Year)",
    icon: "🌾",
    badgeColor: "bg-rose-100 text-rose-800 border-rose-200",
    description: "Cultural festivities, fair admissions, handicraft retail, and sweet shop payments.",
    startDate: "2026-04-10",
    endDate: "2026-04-18",
    businessObjective: "Expand micro-merchant retail adoption and drive cultural festival transactions.",
    targetProduct: "Merchant QR & Micro-Retail",
    availableBudgetBDT: 140000,
    maxCampaignCapacity: 8000,
    eligibleCustomerSegments: ["Lifestyle Enthusiasts", "Young Consumers"],
    preferredChannels: ["Push Notification", "In-App Banner"],
    candidateOffers: [
      CANDIDATE_ACTIONS.cashback_merchant,
      CANDIDATE_ACTIONS.reward_gift_card,
      CANDIDATE_ACTIONS.no_promotional_action,
    ],
    possibleBehaviors: [
      { name: "Fair & Sweets QR Purchase", relevanceRate: 0.83 },
      { name: "Traditional Attire Shopping", relevanceRate: 0.79 },
    ],
  },
  {
    id: "exam_season",
    name: "Exam Season (HSC / BCS / Medical)",
    icon: "📚",
    badgeColor: "bg-sky-100 text-sky-800 border-sky-200",
    description: "Examination form fees, coaching dues, and high-volume connectivity recharge.",
    startDate: "2026-11-01",
    endDate: "2026-11-20",
    businessObjective: "Capture government application fee collections and internet pack refills.",
    targetProduct: "Bill Pay & Mobile Internet",
    availableBudgetBDT: 120000,
    maxCampaignCapacity: 7500,
    eligibleCustomerSegments: ["Aspirants (18-28)", "Students"],
    preferredChannels: ["SMS", "Push Notification"],
    candidateOffers: [
      CANDIDATE_ACTIONS.reminder_recharge,
      CANDIDATE_ACTIONS.cashback_recharge,
      CANDIDATE_ACTIONS.no_promotional_action,
    ],
    possibleBehaviors: [
      { name: "Exam Application Fee Pay", relevanceRate: 0.85 },
      { name: "Data Pack Mobile Recharge", relevanceRate: 0.78 },
    ],
  },
  {
    id: "win_back_season",
    name: "Win-back Season (Q4 Reactivation)",
    icon: "🔄",
    badgeColor: "bg-orange-100 text-orange-800 border-orange-200",
    description: "Dormant user revival through low-frequency, high-intent causal nudges without subsidies.",
    startDate: "2026-11-15",
    endDate: "2026-12-15",
    businessObjective: "Re-engage 30-90 day inactive accounts with minimum marketing burnout.",
    targetProduct: "Recharge & Send Money",
    availableBudgetBDT: 160000,
    maxCampaignCapacity: 8500,
    eligibleCustomerSegments: ["Dormant", "At-Risk", "Win-back"],
    preferredChannels: ["SMS", "In-App Banner"],
    candidateOffers: [
      CANDIDATE_ACTIONS.cashback_recharge,
      CANDIDATE_ACTIONS.insight_money,
      CANDIDATE_ACTIONS.no_promotional_action,
    ],
    possibleBehaviors: [
      { name: "Reactivation Mobile Recharge", relevanceRate: 0.72 },
      { name: "App Open & Balance Inquiry", relevanceRate: 0.65 },
    ],
  },
];

// ─── DEMO SCENARIO EVALUATIONS (SECTIONS 7, 8, 9, 10, 19) ───────────────────

export const DEMO_EVALUATION_DATA: Record<string, CustomerSeasonalEvaluation[]> = {
  // Scenario 1: University Admission Season
  university_admission: [
    {
      customerId: "C1024",
      name: "Student A (Nafis Rahman)",
      phone: "01712-849102",
      avatarSeed: "nafis",
      accountAgeDays: 45,
      lifecycleStage: "Activation",
      predictedBehaviors: [
        { behavior: "Admission Fee Payment", probability: 0.82 },
        { behavior: "Mobile Recharge", probability: 0.61 },
        { behavior: "Merchant QR Payment", probability: 0.34 },
        { behavior: "Send Money", probability: 0.18 },
      ],
      primaryPredictedBehavior: "Admission Fee Payment",
      behaviorConfidence: 0.82,
      seasonalRelevanceScore: 0.94,
      pResponseWithOffer: 0.81,
      pResponseWithoutOffer: 0.27,
      uplift: 0.54, // +54% Uplift!
      upliftSegment: "PERSUADABLE",
      isOrganicProtected: false,
      fatigueScore: 0.18,
      fatigueLevel: "Low",
      fatigueMetrics: {
        offersReceived7d: 1,
        offersReceived30d: 3,
        sameCategoryOfferCount: 0,
        daysSinceLastOffer: 14,
        responseRateTrend: 0.4,
        redemptionRateTrend: 0.35,
        engagementTrend: 0.6,
        categoryFatigue: {
          recharge: 0.22,
          merchant: 0.15,
          sendMoney: 0.10,
          billPay: 0.12,
        },
      },
      recommendedAction: CANDIDATE_ACTIONS.cashback_admission,
      recommendedChannel: "Push Notification",
      recommendedTiming: "7:30 PM",
      expectedTransactionValueBDT: 3200,
      expectedIncrementalValueBDT: 1548.8, // 0.54 * 3200 - 150 * 0.81 - 10 * 0.18
      decisionPriority: "HIGH PRIORITY / TARGET",
      decisionReasoning: [
        "High admission payment intent (82%) detected via partner university portal integration.",
        "New / Activating customer cohort exhibiting maximum sensitivity to initial onboarding incentives.",
        "Substantial incremental uplift (+54%): counterfactual baseline is only 27% without intervention.",
        "Low campaign exposure (only 1 offer in last 7 days) ensures negligible fatigue or annoyance risk.",
        "Optimal delivery window at 7:30 PM coincides with evening study and parental discussion hours.",
      ],
      traceStages: {
        rawData: {
          txCount30d: 2,
          avgSpendBDT: 250,
          lastServiceUsed: "recharge",
          daysSinceLastTx: 6,
        },
        featureVector: {
          rfmScore: "R2-F1-M1 (Low Recency / High Future Potential)",
          categorySaturation: "0% in Education Category",
          contactFrequency: "0.14 contacts/day (Healthy)",
          priceSensitivity: "High (Prefers fee rebates)",
        },
        modelInference: {
          modelName: "T-Learner Causal Forest v3.2",
          tLearnerScore: 0.54,
          intentModelAccuracy: "94.2% ROC-AUC on Student Cohorts",
        },
        counterfactualAnalysis: {
          treatmentResponseRate: "81.0% (P with 10% Cashback)",
          controlBaselineRate: "27.0% (P Organic Baseline)",
          netCausalLift: "+54.0% True Net Incrementality",
        },
        fatigueAssessment: {
          penaltyFactor: 0.18,
          fatigueRecommendation: "Safe to engage. Frequency cap allowance: 2 remaining touches this week.",
        },
        valueOptimization: {
          expectedGrossIncrementalBDT: 1728.0,
          incentiveCostBDT: 121.5,
          netEIVBDT: 1548.8,
        },
        finalAction: {
          actionCode: "ACT-PROMO-ADM-10",
          explanation: "Deploy 10% Admission Cashback via Push Notification at 7:30 PM.",
        },
      },
    },
    {
      customerId: "C1042",
      name: "Tariqul Islam (Organic Protected Student)",
      phone: "01819-332014",
      avatarSeed: "tariqul",
      accountAgeDays: 120,
      lifecycleStage: "Retention",
      predictedBehaviors: [
        { behavior: "Admission Fee Payment", probability: 0.92 },
        { behavior: "Mobile Recharge", probability: 0.75 },
      ],
      primaryPredictedBehavior: "Admission Fee Payment",
      behaviorConfidence: 0.92,
      seasonalRelevanceScore: 0.91,
      pResponseWithOffer: 0.93,
      pResponseWithoutOffer: 0.89,
      uplift: 0.04, // Only +4%!
      upliftSegment: "SURE_THING",
      isOrganicProtected: true,
      organicProtectionReason: "Customer has 89% organic transaction probability. Spending cashback yields only +4% incremental lift, wasting marketing subsidy.",
      fatigueScore: 0.25,
      fatigueLevel: "Low",
      fatigueMetrics: {
        offersReceived7d: 2,
        offersReceived30d: 6,
        sameCategoryOfferCount: 1,
        daysSinceLastOffer: 5,
        responseRateTrend: 0.1,
        redemptionRateTrend: 0.2,
        engagementTrend: 0.4,
        categoryFatigue: { recharge: 0.3, merchant: 0.2, sendMoney: 0.1, billPay: 0.15 },
      },
      recommendedAction: CANDIDATE_ACTIONS.reminder_admission, // Non-promotional!
      recommendedChannel: "Push Notification",
      recommendedTiming: "10:30 AM",
      expectedTransactionValueBDT: 4500,
      expectedIncrementalValueBDT: 180.0,
      decisionPriority: "LOW PRIORITY / NO CASHBACK",
      decisionReasoning: [
        "ORGANIC TRANSACTION PROTECTION: Predicted to pay tuition fees regardless of cashback incentives.",
        "Subsidizing this customer creates deadweight loss of ৳150 without generating incremental behavior.",
        "Switched from costly promotional cashback to a zero-cost informational Admission Deadline Reminder.",
        "Preserves ৳150 marketing budget to reallocate toward true persuadables.",
      ],
      traceStages: {
        rawData: { txCount30d: 9, avgSpendBDT: 1400, lastServiceUsed: "bill_payment", daysSinceLastTx: 2 },
        featureVector: { rfmScore: "R5-F4-M4 (High Value Organic)", categorySaturation: "Moderate", contactFrequency: "Normal", priceSensitivity: "Low" },
        modelInference: { modelName: "T-Learner Causal Forest", tLearnerScore: 0.04, intentModelAccuracy: "96.1%" },
        counterfactualAnalysis: { treatmentResponseRate: "93.0%", controlBaselineRate: "89.0%", netCausalLift: "+4.0% (Incentive Inefficient)" },
        fatigueAssessment: { penaltyFactor: 0.25, fatigueRecommendation: "Protect from unnecessary spam." },
        valueOptimization: { expectedGrossIncrementalBDT: 180.0, incentiveCostBDT: 0.0, netEIVBDT: 180.0 },
        finalAction: { actionCode: "ACT-NONPROMO-ADM-REMINDER", explanation: "Send zero-cost deadline reminder. Suppress monetary cashback." },
      },
    },
    {
      customerId: "C1088",
      name: "Sabrina Yasmin (High Fatigue Risk)",
      phone: "01911-582910",
      avatarSeed: "sabrina",
      accountAgeDays: 210,
      lifecycleStage: "Retention",
      predictedBehaviors: [
        { behavior: "Mobile Recharge", probability: 0.88 },
        { behavior: "Admission Fee Payment", probability: 0.45 },
      ],
      primaryPredictedBehavior: "Mobile Recharge",
      behaviorConfidence: 0.88,
      seasonalRelevanceScore: 0.65,
      pResponseWithOffer: 0.42,
      pResponseWithoutOffer: 0.48,
      uplift: -0.06, // Negative Uplift (Sleeping Dog)!
      upliftSegment: "SLEEPING_DOG",
      isOrganicProtected: false,
      fatigueScore: 0.82,
      fatigueLevel: "High",
      fatigueMetrics: {
        offersReceived7d: 5,
        offersReceived30d: 14,
        sameCategoryOfferCount: 4,
        daysSinceLastOffer: 1,
        responseRateTrend: -0.45,
        redemptionRateTrend: -0.6,
        engagementTrend: -0.5,
        categoryFatigue: { recharge: 0.88, merchant: 0.42, sendMoney: 0.35, billPay: 0.28 },
      },
      recommendedAction: CANDIDATE_ACTIONS.no_promotional_action,
      recommendedChannel: "In-App Banner",
      recommendedTiming: "N/A",
      expectedTransactionValueBDT: 350,
      expectedIncrementalValueBDT: -12.0,
      decisionPriority: "SUPPRESS",
      decisionReasoning: [
        "CRITICAL OFFER FATIGUE: Customer received 5 push notifications in 7 days with declining opens.",
        "Recharge category saturation is at 88% — user shows clear notification exhaustion and annoyance.",
        "Uplift is negative (-6%): further promotional messaging risks app uninstall or notification mute.",
        "MANDATORY DECISION: Strict suppression of all promotional campaigns. Replaced with No Promotional Action.",
      ],
      traceStages: {
        rawData: { txCount30d: 3, avgSpendBDT: 150, lastServiceUsed: "recharge", daysSinceLastTx: 4 },
        featureVector: { rfmScore: "R3-F2-M1 (Fatigued)", categorySaturation: "88% Saturation", contactFrequency: "Over-contacted", priceSensitivity: "Fatigued" },
        modelInference: { modelName: "Decay Anti-Fatigue Neural Net", tLearnerScore: -0.06, intentModelAccuracy: "91.8%" },
        counterfactualAnalysis: { treatmentResponseRate: "42.0%", controlBaselineRate: "48.0%", netCausalLift: "-6.0% (Annoyance Detected)" },
        fatigueAssessment: { penaltyFactor: 0.82, fatigueRecommendation: "Mandatory 14-day promotional blackout." },
        valueOptimization: { expectedGrossIncrementalBDT: -21.0, incentiveCostBDT: 0.0, netEIVBDT: -12.0 },
        finalAction: { actionCode: "ACT-NO-ACTION", explanation: "Zero Promotional Action. Suppress all push alerts." },
      },
    },
  ],

  // Scenario 2: Eid-ul-Fitr Salami Campaign
  eid_ul_fitr: [
    {
      customerId: "C2048",
      name: "Farhan Hossain (C2048)",
      phone: "01755-920194",
      avatarSeed: "farhan",
      accountAgeDays: 310,
      lifecycleStage: "Retention",
      predictedBehaviors: [
        { behavior: "Send Money (Salami)", probability: 0.79 },
        { behavior: "Merchant QR Payment", probability: 0.44 },
        { behavior: "Mobile Recharge", probability: 0.38 },
      ],
      primaryPredictedBehavior: "Send Money (Salami)",
      behaviorConfidence: 0.79,
      seasonalRelevanceScore: 0.98,
      pResponseWithOffer: 0.84,
      pResponseWithoutOffer: 0.39,
      uplift: 0.45, // +45% Uplift!
      upliftSegment: "PERSUADABLE",
      isOrganicProtected: false,
      fatigueScore: 0.14,
      fatigueLevel: "Low",
      fatigueMetrics: {
        offersReceived7d: 1,
        offersReceived30d: 2,
        sameCategoryOfferCount: 0,
        daysSinceLastOffer: 18,
        responseRateTrend: 0.35,
        redemptionRateTrend: 0.4,
        engagementTrend: 0.55,
        categoryFatigue: { recharge: 0.12, merchant: 0.15, sendMoney: 0.08, billPay: 0.10 },
      },
      recommendedAction: CANDIDATE_ACTIONS.cashback_salami,
      recommendedChannel: "Push Notification",
      recommendedTiming: "8:00 PM",
      expectedTransactionValueBDT: 2400,
      expectedIncrementalValueBDT: 1059.0, // 0.45 * 2400 - 25 * 0.84 - 10 * 0.14
      decisionPriority: "HIGH PRIORITY / TARGET",
      decisionReasoning: [
        "Strong historical P2P velocity and high Eid seasonal affinity (Send Money intent 79%).",
        "Large causal uplift (+45%): baseline organic probability is 39% vs 84% with Salami bonus.",
        "Very low recent marketing exposure (last campaign 18 days ago); fatigue is negligible (0.14).",
        "High expected incremental value of ৳1,059 with modest unit incentive cost of only ৳25.",
        "8:00 PM delivery aligns with festive family gatherings and evening digital gift transfers.",
      ],
      traceStages: {
        rawData: { txCount30d: 6, avgSpendBDT: 1800, lastServiceUsed: "send_money", daysSinceLastTx: 3 },
        featureVector: { rfmScore: "R4-F3-M4 (High Value P2P)", categorySaturation: "0% in Send Money", contactFrequency: "Low", priceSensitivity: "Medium" },
        modelInference: { modelName: "T-Learner Uplift Forest", tLearnerScore: 0.45, intentModelAccuracy: "95.5%" },
        counterfactualAnalysis: { treatmentResponseRate: "84.0%", controlBaselineRate: "39.0%", netCausalLift: "+45.0% Net Incremental Lift" },
        fatigueAssessment: { penaltyFactor: 0.14, fatigueRecommendation: "Optimal targeting candidate. Prime timing 8:00 PM." },
        valueOptimization: { expectedGrossIncrementalBDT: 1080.0, incentiveCostBDT: 21.0, netEIVBDT: 1059.0 },
        finalAction: { actionCode: "ACT-PROMO-EID-SALAMI", explanation: "Target with 10% Salami Cashback via Push at 8:00 PM." },
      },
    },
    {
      customerId: "C2090",
      name: "Nusrat Jahan (Organic Salami Sender)",
      phone: "01680-119283",
      avatarSeed: "nusrat",
      accountAgeDays: 450,
      lifecycleStage: "Retention",
      predictedBehaviors: [
        { behavior: "Send Money (Salami)", probability: 0.95 },
        { behavior: "Merchant QR Payment", probability: 0.68 },
      ],
      primaryPredictedBehavior: "Send Money (Salami)",
      behaviorConfidence: 0.95,
      seasonalRelevanceScore: 0.97,
      pResponseWithOffer: 0.94,
      pResponseWithoutOffer: 0.91,
      uplift: 0.03, // +3% Uplift
      upliftSegment: "SURE_THING",
      isOrganicProtected: true,
      organicProtectionReason: "Response with offer: 94%, No offer: 91%, Uplift: +3%. Do not spend cashback on this customer. Customer has high organic transaction probability.",
      fatigueScore: 0.22,
      fatigueLevel: "Low",
      fatigueMetrics: {
        offersReceived7d: 1,
        offersReceived30d: 4,
        sameCategoryOfferCount: 0,
        daysSinceLastOffer: 9,
        responseRateTrend: 0.1,
        redemptionRateTrend: 0.15,
        engagementTrend: 0.3,
        categoryFatigue: { recharge: 0.18, merchant: 0.2, sendMoney: 0.12, billPay: 0.14 },
      },
      recommendedAction: CANDIDATE_ACTIONS.message_eid_greeting, // Zero-cost warm greeting
      recommendedChannel: "In-App Banner",
      recommendedTiming: "9:00 AM",
      expectedTransactionValueBDT: 3500,
      expectedIncrementalValueBDT: 105.0,
      decisionPriority: "LOW PRIORITY / NO CASHBACK",
      decisionReasoning: [
        "ORGANIC TRANSACTION PROTECTION: 91% organic transaction probability without any marketing push.",
        "Cashback incentive produces negligible +3% lift, representing an unnecessary subsidy of ৳25.",
        "Substituted with a personalized Eid Mubarak In-App greeting card with zero marketing cost.",
        "Safeguards organic transaction revenue while preserving customer goodwill.",
      ],
      traceStages: {
        rawData: { txCount30d: 12, avgSpendBDT: 2800, lastServiceUsed: "send_money", daysSinceLastTx: 1 },
        featureVector: { rfmScore: "R5-F5-M5 (VIP Organic P2P)", categorySaturation: "Healthy", contactFrequency: "Low", priceSensitivity: "Incentive-Insensitive" },
        modelInference: { modelName: "T-Learner Uplift Forest", tLearnerScore: 0.03, intentModelAccuracy: "97.2%" },
        counterfactualAnalysis: { treatmentResponseRate: "94.0%", controlBaselineRate: "91.0%", netCausalLift: "+3.0% (Inefficient)" },
        fatigueAssessment: { penaltyFactor: 0.22, fatigueRecommendation: "Do not spam with financial discount prompts." },
        valueOptimization: { expectedGrossIncrementalBDT: 105.0, incentiveCostBDT: 0.0, netEIVBDT: 105.0 },
        finalAction: { actionCode: "ACT-NONPROMO-GREETING", explanation: "Deliver personalized festive greeting. Exclude from cashback pool." },
      },
    },
    {
      customerId: "C2115",
      name: "Tanvir Anam (Multi-Offer Saturated)",
      phone: "01711-499102",
      avatarSeed: "tanvir",
      accountAgeDays: 180,
      lifecycleStage: "Win-back",
      predictedBehaviors: [
        { behavior: "Send Money (Salami)", probability: 0.52 },
        { behavior: "Mobile Recharge", probability: 0.48 },
      ],
      primaryPredictedBehavior: "Send Money (Salami)",
      behaviorConfidence: 0.52,
      seasonalRelevanceScore: 0.70,
      pResponseWithOffer: 0.35,
      pResponseWithoutOffer: 0.40,
      uplift: -0.05,
      upliftSegment: "SLEEPING_DOG",
      isOrganicProtected: false,
      fatigueScore: 0.76,
      fatigueLevel: "High",
      fatigueMetrics: {
        offersReceived7d: 4,
        offersReceived30d: 11,
        sameCategoryOfferCount: 3,
        daysSinceLastOffer: 2,
        responseRateTrend: -0.3,
        redemptionRateTrend: -0.4,
        engagementTrend: -0.35,
        categoryFatigue: { recharge: 0.45, merchant: 0.3, sendMoney: 0.76, billPay: 0.2 },
      },
      recommendedAction: CANDIDATE_ACTIONS.no_promotional_action,
      recommendedChannel: "In-App Banner",
      recommendedTiming: "N/A",
      expectedTransactionValueBDT: 800,
      expectedIncrementalValueBDT: -15.0,
      decisionPriority: "SUPPRESS",
      decisionReasoning: [
        "Received 3 Send Money push alerts in the last 72 hours; P2P fatigue reached 76%.",
        "Model predicts negative uplift (-5%): promotional notification increases churn likelihood.",
        "Suppressed to protect long-term customer relationship during festive peak.",
      ],
      traceStages: {
        rawData: { txCount30d: 2, avgSpendBDT: 400, lastServiceUsed: "send_money", daysSinceLastTx: 8 },
        featureVector: { rfmScore: "R2-F2-M2 (Fatigued Dormant)", categorySaturation: "High", contactFrequency: "Excessive", priceSensitivity: "Fatigued" },
        modelInference: { modelName: "T-Learner Uplift Forest", tLearnerScore: -0.05, intentModelAccuracy: "92.0%" },
        counterfactualAnalysis: { treatmentResponseRate: "35.0%", controlBaselineRate: "40.0%", netCausalLift: "-5.0% Churn Penalty" },
        fatigueAssessment: { penaltyFactor: 0.76, fatigueRecommendation: "Immediate 10-day promotional cooldown." },
        valueOptimization: { expectedGrossIncrementalBDT: -20.0, incentiveCostBDT: 0.0, netEIVBDT: -15.0 },
        finalAction: { actionCode: "ACT-NO-ACTION", explanation: "Hold and suppress. No promotional outreach." },
      },
    },
  ],

  // Scenario 3: Salary / Month-End Cycle
  salary_month_end: [
    {
      customerId: "C3012",
      name: "Kamrul Hassan (Salaried Executive)",
      phone: "01720-883192",
      avatarSeed: "kamrul",
      accountAgeDays: 520,
      lifecycleStage: "Retention",
      predictedBehaviors: [
        { behavior: "Utility Bill Payment", probability: 0.89 },
        { behavior: "Salary Bank Cash-In", probability: 0.81 },
      ],
      primaryPredictedBehavior: "Utility Bill Payment",
      behaviorConfidence: 0.89,
      seasonalRelevanceScore: 0.95,
      pResponseWithOffer: 0.88,
      pResponseWithoutOffer: 0.42,
      uplift: 0.46,
      upliftSegment: "PERSUADABLE",
      isOrganicProtected: false,
      fatigueScore: 0.16,
      fatigueLevel: "Low",
      fatigueMetrics: {
        offersReceived7d: 1,
        offersReceived30d: 3,
        sameCategoryOfferCount: 0,
        daysSinceLastOffer: 12,
        responseRateTrend: 0.25,
        redemptionRateTrend: 0.3,
        engagementTrend: 0.4,
        categoryFatigue: { recharge: 0.15, merchant: 0.2, sendMoney: 0.1, billPay: 0.11 },
      },
      recommendedAction: CANDIDATE_ACTIONS.reminder_utility,
      recommendedChannel: "Push Notification",
      recommendedTiming: "9:00 AM",
      expectedTransactionValueBDT: 3800,
      expectedIncrementalValueBDT: 1748.0,
      decisionPriority: "HIGH PRIORITY / TARGET",
      decisionReasoning: [
        "Month-end payroll cycle matches utility bill due dates; high intent for electricity and water.",
        "Zero-cost reminder delivers +46% uplift without requiring expensive cashback incentives.",
        "High expected incremental GMV of ৳1,748 with minimal budget impact.",
      ],
      traceStages: {
        rawData: { txCount30d: 8, avgSpendBDT: 2400, lastServiceUsed: "bill_payment", daysSinceLastTx: 4 },
        featureVector: { rfmScore: "R4-F4-M4 (Salaried Pro)", categorySaturation: "Low", contactFrequency: "Low", priceSensitivity: "Low" },
        modelInference: { modelName: "T-Learner Uplift Forest", tLearnerScore: 0.46, intentModelAccuracy: "96.4%" },
        counterfactualAnalysis: { treatmentResponseRate: "88.0%", controlBaselineRate: "42.0%", netCausalLift: "+46.0% Lift" },
        fatigueAssessment: { penaltyFactor: 0.16, fatigueRecommendation: "Safe for high-priority notification." },
        valueOptimization: { expectedGrossIncrementalBDT: 1748.0, incentiveCostBDT: 0.0, netEIVBDT: 1748.0 },
        finalAction: { actionCode: "ACT-NONPROMO-UTIL-REMINDER", explanation: "Deploy morning utility due reminder at 9:00 AM." },
      },
    },
  ],

  // Scenario 4: Shopping Season & Flash Deals
  shopping_season: [
    {
      customerId: "C4018",
      name: "Ayesha Siddiqua (Retail Shopper)",
      phone: "01844-902194",
      avatarSeed: "ayesha",
      accountAgeDays: 160,
      lifecycleStage: "Acquisition",
      predictedBehaviors: [
        { behavior: "Merchant QR Payment", probability: 0.86 },
        { behavior: "Online E-Commerce", probability: 0.72 },
      ],
      primaryPredictedBehavior: "Merchant QR Payment",
      behaviorConfidence: 0.86,
      seasonalRelevanceScore: 0.92,
      pResponseWithOffer: 0.85,
      pResponseWithoutOffer: 0.32,
      uplift: 0.53,
      upliftSegment: "PERSUADABLE",
      isOrganicProtected: false,
      fatigueScore: 0.20,
      fatigueLevel: "Low",
      fatigueMetrics: {
        offersReceived7d: 1,
        offersReceived30d: 4,
        sameCategoryOfferCount: 1,
        daysSinceLastOffer: 8,
        responseRateTrend: 0.3,
        redemptionRateTrend: 0.4,
        engagementTrend: 0.5,
        categoryFatigue: { recharge: 0.1, merchant: 0.18, sendMoney: 0.15, billPay: 0.1 },
      },
      recommendedAction: CANDIDATE_ACTIONS.cashback_merchant,
      recommendedChannel: "Push Notification",
      recommendedTiming: "5:00 PM",
      expectedTransactionValueBDT: 1850,
      expectedIncrementalValueBDT: 916.75,
      decisionPriority: "HIGH PRIORITY / TARGET",
      decisionReasoning: [
        "Pre-festival shopping intent peaked at 86% based on browsing partner brands in Upay hub.",
        "+53% net causal uplift from 15% Merchant QR cashback with ৳75 expected unit cost.",
        "Timing at 5:00 PM aligns with evening retail shopping foot-traffic peak.",
      ],
      traceStages: {
        rawData: { txCount30d: 4, avgSpendBDT: 950, lastServiceUsed: "merchant_payment", daysSinceLastTx: 3 },
        featureVector: { rfmScore: "R3-F2-M3 (Active Shopper)", categorySaturation: "Low", contactFrequency: "Low", priceSensitivity: "High" },
        modelInference: { modelName: "T-Learner Uplift Forest", tLearnerScore: 0.53, intentModelAccuracy: "94.8%" },
        counterfactualAnalysis: { treatmentResponseRate: "85.0%", controlBaselineRate: "32.0%", netCausalLift: "+53.0% Lift" },
        fatigueAssessment: { penaltyFactor: 0.20, fatigueRecommendation: "Approved for merchant campaign." },
        valueOptimization: { expectedGrossIncrementalBDT: 980.5, incentiveCostBDT: 63.75, netEIVBDT: 916.75 },
        finalAction: { actionCode: "ACT-PROMO-MERCH-15", explanation: "Deliver 15% Merchant QR Cashback at 5:00 PM." },
      },
    },
  ],
};

// ─── INITIAL CALENDAR DATA (SECTION 13 & 14) ────────────────────────────────

export const SEASONAL_CALENDAR_ITEMS: SeasonalCampaignCalendarCard[] = [
  {
    id: "cal-oct-admission",
    title: "University Admission Season",
    icon: "🎓",
    dateRange: "Oct 1 – Oct 31, 2026",
    month: "OCTOBER",
    status: "ACTIVE",
    targetAudience: "New Admissions & Students (12,000 Cap)",
    budgetBDT: 280000,
    aiConfidence: 0.94,
    fatigueRisk: "Low",
    expectedIncrementalValueBDT: 742000,
    primaryMetric: "+54% Student Lift",
    whyNowChecks: [
      { label: "Seasonal demand is increasing", passed: true, detail: "Public & private university admission deadlines peaking this month." },
      { label: "Relevant customer behaviour detected", passed: true, detail: "82% intent predicted among 18-24 youth demographic." },
      { label: "Historical campaign response is positive", passed: true, detail: "Previous admission campaigns achieved 3.8x incremental ROI." },
      { label: "Expected uplift is above baseline", passed: true, detail: "Net causal lift exceeds +40% across target persuadable tier." },
      { label: "Customer fatigue is low", passed: true, detail: "Average touches in last 7 days: 0.9 contacts/user." },
      { label: "Budget availability is sufficient", passed: true, detail: "৳2.8L fully optimized via Knapsack linear solver." },
    ],
  },
  {
    id: "cal-oct-eid",
    title: "Eid Salami & Festive Transfer",
    icon: "🌙",
    dateRange: "Oct 8 – Oct 15, 2026",
    month: "OCTOBER",
    status: "AI OPTIMIZED",
    targetAudience: "P2P Remitters & Families (25,000 Cap)",
    budgetBDT: 550000,
    aiConfidence: 0.96,
    fatigueRisk: "Low",
    expectedIncrementalValueBDT: 1485000,
    primaryMetric: "+45% P2P Volume Lift",
    whyNowChecks: [
      { label: "Seasonal demand is increasing", passed: true, detail: "Festive remittance velocity up 210% historically in this window." },
      { label: "Relevant customer behaviour detected", passed: true, detail: "Send Money affinity detected for 79% of target cohort." },
      { label: "Historical campaign response is positive", passed: true, detail: "Previous Eid campaign drove 31,400 incremental transfers." },
      { label: "Expected uplift is above baseline", passed: true, detail: "Causal uplift calculated at +45% against control group." },
      { label: "Customer fatigue is low", passed: true, detail: "Anti-fatigue decay caps exposure to max 1 offer per 10 days." },
      { label: "Budget availability is sufficient", passed: true, detail: "Allocated ৳5.5L reflecting high incremental elasticity." },
    ],
  },
  {
    id: "cal-oct-shopping",
    title: "Shopping & Merchant Flash Wave",
    icon: "🛒",
    dateRange: "Oct 15 – Oct 30, 2026",
    month: "OCTOBER",
    status: "AI RECOMMENDED",
    targetAudience: "Urban QR Shoppers (9,000 Cap)",
    budgetBDT: 170000,
    aiConfidence: 0.89,
    fatigueRisk: "Medium",
    expectedIncrementalValueBDT: 420000,
    primaryMetric: "+38% POS QR Lift",
    whyNowChecks: [
      { label: "Seasonal demand is increasing", passed: true, detail: "Pre-winter retail discount promotions launched by top retail chains." },
      { label: "Relevant customer behaviour detected", passed: true, detail: "Merchant payment probability exceeds 65% for target cluster." },
      { label: "Historical campaign response is positive", passed: true, detail: "2.5x incremental gross transaction return." },
      { label: "Expected uplift is above baseline", passed: true, detail: "+38% predicted lift over untreated baseline." },
      { label: "Customer fatigue is low", passed: false, detail: "Medium risk: some retail shoppers received multiple weekend pushes." },
      { label: "Budget availability is sufficient", passed: true, detail: "৳1.7L allocated within knapsack ceiling." },
    ],
  },
  {
    id: "cal-oct-salary",
    title: "Salary & Utility Settlement",
    icon: "💼",
    dateRange: "Oct 25 – Oct 31, 2026",
    month: "OCTOBER",
    status: "SCHEDULED",
    targetAudience: "Household Bill Payers (15,000 Cap)",
    budgetBDT: 200000,
    aiConfidence: 0.93,
    fatigueRisk: "Low",
    expectedIncrementalValueBDT: 610000,
    primaryMetric: "+41% Zero-Cost Bill Lift",
    whyNowChecks: [
      { label: "Seasonal demand is increasing", passed: true, detail: "Month-end salary credits trigger predictable bill due dates." },
      { label: "Relevant customer behaviour detected", passed: true, detail: "DPDC/DESCO utility payment affinity detected in 89% of cohort." },
      { label: "Historical campaign response is positive", passed: true, detail: "High retention with 98% timely settlement." },
      { label: "Expected uplift is above baseline", passed: true, detail: "+41% lift achieved with non-promotional reminders." },
      { label: "Customer fatigue is low", passed: true, detail: "Zero promotional clutter; informational nudge only." },
      { label: "Budget availability is sufficient", passed: true, detail: "৳2.0L allocated for selective cashback on new billers." },
    ],
  },
];

// ─── EXPERIMENT & LEARNING REPORTS (SECTIONS 15 & 16) ────────────────────────

export const CAMPAIGN_LEARNING_REPORTS: CampaignLearningReport[] = [
  {
    id: "rep-eid-salami-2026",
    campaignName: "Eid Salami Cashback Wave 1",
    eventName: "Eid-ul-Fitr",
    dateConducted: "March 2026",
    targetedAudience: 185000,
    treatmentAudience: 92500, // 50/50 RCT
    controlAudience: 92500,
    predictedUplift: 0.42, // +42%
    actualUplift: 0.38, // +38%
    predictionGapPoints: 4.0, // 4 percentage points error
    incrementalTransactions: 31400,
    campaignCostBDT: 1850000,
    incrementalValueBDT: 4620000,
    netIncrementalROI: 2.50,
    fatigueChangePct: 3.2,
    statisticalConfidence: 0.99,
    isSignificant: true,
    aiKeyLearning: "Send Money cashback performed strongly (+38% actual lift) among high-frequency P2P users, but showed lower incremental impact among customers with already-high organic transaction probability (>85%). In future campaigns, automatic Organic Transaction Protection must suppress cashback for these users, redirecting budget to pure persuadables.",
    feedbackToModels: [
      "Updated T-Learner prior: Lowered subsidy sensitivity weight for customers with >10 lifetime P2P transactions.",
      "Added Organic Transaction Protection threshold at P(Response | No Offer) >= 0.85.",
      "Calibrated Send Money fatigue decay factor from 0.80 to 0.72 to allow faster post-festive cooldown.",
    ],
  },
  {
    id: "rep-admission-2026",
    campaignName: "University Intake Pilot",
    eventName: "University Admission Season",
    dateConducted: "September 2026",
    targetedAudience: 45000,
    treatmentAudience: 36000, // 80/20 RCT
    controlAudience: 9000,
    predictedUplift: 0.48,
    actualUplift: 0.45,
    predictionGapPoints: 3.0,
    incrementalTransactions: 16200,
    campaignCostBDT: 675000,
    incrementalValueBDT: 2430000,
    netIncrementalROI: 3.60,
    fatigueChangePct: 1.1,
    statisticalConfidence: 0.98,
    isSignificant: true,
    aiKeyLearning: "Non-promotional deadline alerts delivered 80% of the incremental conversion of cashbacks when delivered between 7:00 PM and 8:30 PM. Student cohorts responded strongly to zero-cost informational nudges, reducing blended cost per incremental acquisition by 44%.",
    feedbackToModels: [
      "Promoted 'Admission Deadline Reminder' to default candidate action for Activation-stage students.",
      "Refined optimal timing window to 7:30 PM for education payment category.",
    ],
  },
];
